version: '2'
catalog:
  name: "AWX Container for Rancher"
  version: "1.0.0"
  description: "Configuration Managment with ansible web client former tower"
  uuid: awx-1
  minimum_rancher_version: v0.46.0
services:
  postgres:
    scale: 1
    start_on_create: true
  rabbitmq:
    scale: 1
    start_on_create: true
  awx_web:
    scale: 1
    start_on_create: true
  awx_task:
    scale: 1
    start_on_create: true
